### ISSUE TITLE
typescript signatures for clientConfiguration/serverConfiguration do not include options

### ISSUE THREAD

**Issue by alecf** [catamphetamine/universal-webpack#104]
in https://github.com/catamphetamine/universal-webpack/blob/master/index.d.ts, the 3rd option to `clientConfiguration` / `serverConfiguration` is missing the `options` parameter:

https://github.com/catamphetamine/universal-webpack/blob/master/index.d.ts

which means you can't call this from typescript without jumping through some hoops!

**Comment by catamphetamine** [comment]
Released `universal-webpack@0.6.10` with the fix.
Didn't check if it works (I don't use TypeScript).

**Comment by alecf** [comment]
thanks!
