### ISSUE TITLE
Advanced config

### ISSUE THREAD

**Issue by abiagent007** [catamphetamine/universal-webpack#106]
Hi, I passed the advanced config to the function 'serverConfiguration' as third parameter.

```js
const { serverConfiguration } = require('universal-webpack');
const settings = require('./universal-webpack-settings');
const baseConfiguration = require('./webpack.server.config');

process.env.UNIVERSAL_WEBPACK_CSS_LOADER_V2 = true;

const configuration = (env, { mode }) =>
  serverConfiguration(baseConfiguration(env, { mode }), settings, {
      excludeFromExternals: [
        'lodash-es',
        ' ... ',
        /^some-other-es6-only-module(\/.*)?$/,
      ],
      loadExternalModuleFileExtensions: ['css', 'png', 'jpg', 'svg', 'xml'],
      silent: true,
      chunk_info_filename: 'webpack-chunks-test.json',
      development: mode !== 'production',
});

module.exports = configuration;
```

Is this done correctly? It seems like chunk_info_filename has no effect, because it remains the default (`webpack-chunks.json`). I'm not sure now, if the remain of the advanced config gets used.

**Comment by catamphetamine** [comment]
> Is this done correctly?

Depends on what you wanted to achieve.

> It seems like chunk_info_filename has no effect

You can test that by adding `console.log` to `node_modules/universal-webpack/build/chunks plugin.js`.

**Comment by abiagent007** [comment]
Thank you, catamphetamine for helping me!

> > Is this done correctly?
> 
> Depends on what you wanted to achieve.
> 

I want to achieve what these properties do according to the advanced config sample of the readme.

> > It seems like chunk_info_filename has no effect
> 
> You can test that by adding `console.log` to `node_modules/universal-webpack/build/chunks plugin.js`.

After doing this, it seems like the function `serverConfiguration` doesn't use the `ChunkFileNamesPlugin`, but the function `clientConfiguration` does use it.
I found that out by running webpack with each config (client and server) separated.

This is how my client config looks:

```
const { clientConfiguration } = require('universal-webpack');
const settings = require('./universal-webpack-settings');
const baseConfiguration = require('./webpack.config');

const configuration = (env, { mode }) =>
  clientConfiguration(baseConfiguration(env, { mode }), settings, {
    // Extract all CSS into separate `*.css` files (one for each chunk)
    // using `mini-css-extract-plugin`
    // instead of leaving that CSS embedded directly in `*.js` chunk files.
    development: mode !== 'production',
    useMiniCssExtractPlugin: true,
    chunk_info_filename: 'webpack-chunks-test.json',
    silent: true,
  });

// Create client-side Webpack config.
module.exports = configuration;
```

This is what console logging in the chunks plugin ouputs by running webpack with the client config.
`{ silent: undefined, chunk_info_filename: undefined }`

Running webpack with the server config results in no console logging - no output, except the default lines.

Somehow the advanced config doesn't get passed to the plugin. I assume I try to pass the advanced config at the wrong place?

In the sample project only the function `clientConfiguration` passes three parameters, whereas the function `serverConfiguration` gets only two parameters passed. Does `serverConfiguration` accept three parameters?

In general I just like to know where to pass the advanced config for the client and the server.

**Comment by catamphetamine** [comment]
> Running webpack with the server config results in no console logging - no output, except the default lines.

Yes, it doesn't use the plugin.
Only client-side Webpack build does.

> Somehow the advanced config doesn't get passed to the plugin. I assume I try to pass the advanced config at the wrong place?

Yes, you should move those config parameters inside `settings`.

> Does `serverConfiguration` accept three parameters?

No.

> In general I just like to know where to pass the advanced config for the client and the server.

In the second argument.

**Comment by abiagent007** [comment]
It works now.
I found out that the advanced config must be passed to `serverConfiguration` with the settings file (`universal-webpack-settings.json`).

```
{
    "server":
    {
      "input": "./source/server.js",
      "output": "./build/server/server.js"
    },
    "excludeFromExternals": [
        "lodash-es",
        " ... "
    ],
    "loadExternalModuleFileExtensions": ["css", "png", "jpg", "svg", "xml"],
    "silent": true,
    "chunk_info_filename": "webpack-chunks-test.json",
    "development": true
  }
```

I suggest to make it more obvious in the readme.

...by writing this I notice that you answered just a moment ago. Thank you, catamphetamine! :)
And thanks to you and all the other contributors for this project! :D

**Comment by catamphetamine** [comment]
> I suggest to make it more obvious in the readme.

Ok, added the clarification to the readme .
