### ISSUE TITLE
How to config webpack-chunks.json path?

### ISSUE THREAD

**Issue by susan-github** [catamphetamine/universal-webpack#108]
Config the server.output look like './static/dist/server.js', the webpack-chunks.json file will be built to output path, because of the old project using ”clean-webpack-plugin“ plugin, so the dist folder will be removed which caused 'universal-webpack' find './static/dist' failed.

If you have any suggestions?  If there has any way to config webpack-chunks.json path individually.

`{
    "server":
    {
        "input": "./src/server/index.js",
        "output": "./static/dist/server.js"
    },
    "loadExternalModuleFileExtensions": ["css", "png", "jpg", "svg", "xml"],
    "silent": true,
    "chunk_info_filename": "webpack-chunks.json"
}`

**Comment by catamphetamine** [comment]
The example project uses `clean-webpack-plugin` and it works.
https://github.com/catamphetamine/webpack-react-redux-server-side-render-example
That project builds server in `build/server` and client in `build/assets` and `webpack-chunks.json` is generated in `build` so it's not cleared: only `build/assets` is cleared.

**Comment by catamphetamine** [comment]
Actually, my answer wasn't 100% correct: `webpack-chunks.json` is not output in `build`, it's output in `build/assets` and `build/assets` is cleaned:

![image](https://user-images.githubusercontent.com/477167/57924165-12b46b80-78ad-11e9-9608-f83449aac2dc.png)

I guess your issue is that you run `clean` plugin after `universal-webpack` plugin.

**Comment by catamphetamine** [comment]
The code adds `universal-webpack` plugin after `clean` plugin so normally `universal-webpack` plugin can't run before `clean`.
https://github.com/catamphetamine/universal-webpack/blob/3b022b50ed211a135525dcca9fe469a480abec69/source/client%20configuration.js#L18-L34
Examine your resulting webpack config and see the order.
