### ISSUE TITLE
Compatibility with css-loader@3 broken

### ISSUE THREAD

**Issue by Reeywhaar** [catamphetamine/universal-webpack#109]
Hello! Thank you for the great lib, first of all :-)

`css-loader` v3 was shipped out recently, and in breaking changes it [has](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes):

> exportOnlyLocals option was remove in favor onlyLocals option

I see that `universal-webpack` adds `exportOnlyLocals` to server config.

**Comment by catamphetamine** [comment]
See `universal-webpack@0.6.12`

**Comment by Reeywhaar** [comment]
Whoa! What a speed! Thank you so much!
