### ISSUE TITLE
url-loader doesnt have an emitFile option

### ISSUE THREAD

**Issue by davidfurlong** [catamphetamine/universal-webpack#85]
https://github.com/catamphetamine/universal-webpack/blob/master/source/server%20configuration.js#L237

https://github.com/webpack-contrib/url-loader#options

**Comment by catamphetamine** [comment]
https://github.com/webpack-contrib/url-loader/blob/2de70bb7b17e460c347b480e561067c8177b66b8/index.js#L34-L36

![http://i2.kym-cdn.com/photos/images/facebook/000/531/557/a88.jpg](http://i2.kym-cdn.com/photos/images/facebook/000/531/557/a88.jpg)

**Comment by davidfurlong** [comment]
![image](https://user-images.githubusercontent.com/614768/29116583-842a80f6-7cfb-11e7-99c0-e45ac09bdfa6.png)

Doc formatting 🥇
