### ISSUE TITLE
babel-register aleary use source-map-support!

### ISSUE THREAD

**Issue by FTAndy** [catamphetamine/universal-webpack#86]
I want to use the source map with universal-webpack and babel, but babel-register aleardy use `source-map-support`,  which change the node default error handler. If I `import 'source-map-support/register'`, it will change it twice, which cause the source map output the wrong path.

And I find out when babel-register use `source-map-support`, it map from the memory running code to the complied file, not from complied file to all source files. How can I generate right source map? @catamphetamine

**Comment by catamphetamine** [comment]
I'm not a source map expert and I'm ok with what the sample project has.
If you happen to find a solution for your case you may post it here.
If it happens to be a generic solution I'll add it to the readme.

**Comment by FTAndy** [comment]
I run [example-node-server](https://github.com/babel/example-node-server), and find that `babel-register` just map from running code to file, without webpack it is great. With webpack and babel-register, though webpack can produce a `.map` file, it never will be used. So the real source map function cannot be used. But only if you use webpack and source-map-support, not with babel-register.@catamphetamine

**Comment by FTAndy** [comment]
which make universal-webpack can not be used in production, because debug webpack file in production is a disaster.

**Comment by FTAndy** [comment]
@catamphetamine just need to remove `babel-register` and add `source-map-support`, and every thing works. Add this to readme, `babel-register` is not necessary.

**Comment by catamphetamine** [comment]
I'm not a source map expert so a precise steps instruction is gonna be required if you want this to be added to the readme.

**Comment by FTAndy** [comment]
`babel-register` use  `source-map-support` by default, and compile code in runtime, which will make node error stack out of order. you can  debug in `babel-register`'s node_modules `source-map-support`'s `source-map-support.js` file, where `prepareStackTrace` will take care of the native `prepareStackTrace` function and process compiled file to the source file.

but if you disable `babel-register` and enable `source-map-support` to the top of `server.js`, and run the `server.js` file, then `throw new Error('aaa')`, the output error stack log will be right. but was wrong when enable `babel-register` and disable `source-map-support`.@catamphetamine

**Comment by FTAndy** [comment]
if you want a demo, i can demo it

**Comment by catamphetamine** [comment]
I see, so `babel-register` has its own source maps generated which screws line numbers up.
Removing `babel-register` from the readme then.
Thx.
