### ISSUE TITLE
got an error when extracting css with extract-text-webpack-plugin.

### ISSUE THREAD

**Issue by robert7git** [catamphetamine/universal-webpack#87]
Hello there
I was having problems with universal-webpack.

I tried `import draft-js-focus-plugin / lib / plugin.css`

Both of client-side and server-side are packed and seems going well
But I got an error message when I started serveride-render-service with npm
  The

     `"dev: server": "nodemon ./src/ssr/start.babel --watch ./dist/server"`

I got an error message
/xxxprojectPath/xxxxprojectName/node_modules/draft-js-focus-plugin/lib/plugin.css: 1
(function (exports, require, module, __filename, __dirname) {.draftJsFocusPlugin__unfocused__1Wvrs: hover {

Hear is my relevant code

#react component
```
import React from 'react'
import 'draft-js-focus-plugin/lib/plugin.css';
import './scss.scss';
// import './css.css';
const component = (props) => {
  return(
    <div>
      App
    </div>
  )
}

export default component
```

#rules of webpack.config
```
rules: [
      {
        test: /\.(js|jsx)$/,
        loader: 'babel-loader'
      },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract([{ loader: 'css-loader' }])
      },
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract([
          {
            loader: 'css-loader',
            options: {
              modules: true,
              importLoaders: 1,
              sourceMap: true,
              camelCase: true,
              localIdentName: '[path]_[name]_[local]___[hash:base64:5]'
            },
          },
          {
            loader: 'sass-loader'
          }
        ])
      }
    ]
```

**Comment by catamphetamine** [comment]
I'm closing this since `universal-webpack` doesn't run anything, it just generates configuration files for Webpack.

**Comment by robert7git** [comment]
Sorry，maybe, I am not clear enough to express.
Now I have solved it.
Still thank you for your reply.
