### ISSUE TITLE
Allow oneOf inside a module rule

### ISSUE THREAD

**Issue by joewestcott** [catamphetamine/universal-webpack#88]
I'm getting the error:
`Neither "loaders" nor "loader" nor "use" are present inside a module rule:`
when I have a rule with a `oneOf`

more info: https://webpack.js.org/configuration/module/#rule-oneof

**Comment by catamphetamine** [comment]
Does it output the rule?

**Comment by joewestcott** [comment]
It gets to here and throws an error: https://github.com/catamphetamine/universal-webpack/blob/7b7294d3c1bcac6c063e65d6dc5e46dba7ff60f2/source/loaders.js#L142

**Comment by catamphetamine** [comment]
Does it output the rule?

**Comment by joewestcott** [comment]
It throws the error before getting to an output.

**Comment by catamphetamine** [comment]
The output is the error itself.
Post the full error.

**Comment by joewestcott** [comment]
It does output the rule along with the error, yes.
The link in my first post contains an example `oneOf` rule it also failed on.

**Comment by catamphetamine** [comment]
The fix is going to take some time

**Comment by catamphetamine** [comment]
Released version `0.6.0`.

**Comment by joewestcott** [comment]
Hey @catamphetamine, Thankyou for this!
