### ISSUE TITLE
extract-text-webpack-plugin deprecated

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [catamphetamine/universal-webpack#92]
Hey guys,

It looks like one dependency extract-text-webpack-plugin is deprecated. 
It doesn't support latest version of webpack.

https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/758

Could you switch to https://github.com/webpack-contrib/mini-css-extract-plugin ?

**Comment by catamphetamine** [comment]
There's no `extract-text-webpack-plugin` dependency

**Comment by Iuriy-Budnikov** [comment]
@catamphetamine 

```
Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at create_extract_css_plugin (/node_modules/universal-webpack/build/client configuration.js:210:26)
    at client_configuration (/node_modules/universal-webpack/build/client configuration.js:76:28)
    at _default (/webpack/webpack.config.client.js:6:10)
    at Object.<anonymous> (/webpack/webpack.config.client.development.js:7:20)
    at Module._compile (module.js:643:30)
    at loader (/node_modules/babel-register/lib/node.js:144:5)
```

**Comment by catamphetamine** [comment]
Post the version of the library and the code where you're calling it

**Comment by Iuriy-Budnikov** [comment]
The version is `"universal-webpack": "^0.6.2"`
It placed in the build.

![screen shot 2018-03-31 at 10 17 00 pm](https://user-images.githubusercontent.com/3968373/38166740-6f5f0f04-3531-11e8-808f-9f36852e17c6.png)

**Comment by catamphetamine** [comment]
Post the code where you're calling the library's function

**Comment by Iuriy-Budnikov** [comment]
hm, it looks like i still need to install manually `extract-text-webpack-plugin`

**Comment by catamphetamine** [comment]
This is not complete code.
Anyway, if your project was based on `webpack-react-redux-isomorphic-example` then there's a certain upgrade process when moving to Webpack 4.
See this commit for reference:
https://github.com/catamphetamine/webpack-react-redux-isomorphic-render-example/commit/385bac3c6ac78d4a8159074ec7119d4bad3f5952
For instance, `webpack.config.client.production.babel.js` should include `useMiniCssExtractPlugin: true`.
And if you were using `import { devtools } from 'universal-webpack'` before then it's `import { smokeScreen, hideSmokeScreen } from 'universal-webpack'` for Webpack 4.

**Comment by catamphetamine** [comment]
> hm, it looks like i still need to install manually extract-text-webpack-plugin

You don't

**Comment by Iuriy-Budnikov** [comment]
Thanks `useMiniCssExtractPlugin: true` resolved an issue

**Comment by catamphetamine** [comment]
And also `cssBundle: true` option should be removed from `webpack/webpack.config.client.development.js`
