### ISSUE TITLE
Nodemon causes Error 503 on Hot reload

### ISSUE THREAD

**Issue by tavurth** [catamphetamine/universal-webpack#95]
From the docs:

> I recommend using nodemon for running server-side Webpack bundle. Nodemon has a --watch <directory> command line parameter which restarts Node.js process each time the <directory> is updated (e.g. each time any file in that directory is modified).

However because the servers compiled file builds every time the client components change, the server reloads, breaking HMR.

Perhaps someone has already solved this for one of their projects?

**Comment by catamphetamine** [comment]
> However because the servers compiled file builds every time the client components change, the server reloads, breaking HMR.

It doesn't break any HMR because HMR is handled by `webpack-dev-server` and not by `nodemon`.
Btw `webpack-serve` is recommended instead of `webpack-dev-server`.

**Comment by tavurth** [comment]
@catamphetamine I'm actually using `webpack-serve` but it's still giving me a `503` error.

**Comment by catamphetamine** [comment]
See https://github.com/catamphetamine/webpack-react-redux-server-side-render-example
If you happen to catch the error there then you can post here.
Otherwise the issue is considered specific to your setup.

**Comment by tavurth** [comment]
In my `package.json` I have the following scripts:

```json
"scripts": {
        "watch:dev:ssr": "NODE_ENV=development nodemon ./webpack/run-ssr --watch ./dist/server",
	"watch:server": "NODE_ENV=development webpack --progress --watch --config ./webpack/config.server.babel.js",
	"watch:client": "NODE_ENV=development webpack-serve --progress --watch --port 3002 --host 0.0.0.0 --config ./webpack/config.client.babel.js",
}
```

And I see that from the attached example you use the `delay` script:
```json
"scripts": {
	"dev": "npm-run-all development:client:rendering-service:build:prepare development",
	"development": "npm-run-all --parallel development:client:build development:client:rendering-service:build development:services",
	"development:client:rendering-service:build:prepare": "universal-webpack --settings ./webpack/universal-webpack-settings.json prepare",
	"development:client:build": "webpack-serve --hot --require babel-register --config webpack/webpack.config.client.development.babel.js",
	"development:client:rendering-service:build": "webpack --mode development --config ./webpack/webpack.config.server.development.babel.js --watch --colors --display-error-details",
	"development:api": "nodemon ./api-server/index.entry.js --watch ./api",
	"development:client:rendering-service": "nodemon ./rendering-service/index.entry.js --watch ./rendering-service --watch ./build/server",
	"development:client:rendering-service:delayed": "npm-run-all delay development:client:rendering-service",
	"development:proxy": "nodemon ./proxy-server/index.entry.js --watch ./proxy-server",
	"development:proxy:delayed": "npm-run-all delay delay development:proxy",
	"development:services": "npm-run-all --parallel development:api development:client:rendering-service:delayed development:proxy:delayed",
}
```

However running scripts such as 

`"development:proxy:delayed": "npm-run-all delay delay development:proxy",` seems very hacky, and dependent on the development machines compilation speed.

Perhaps we could integrate a watching system for `webpack-serve` so that it can delay until the server has finished building and restarting?

**Comment by catamphetamine** [comment]
`delay` is only for fixing `nodemon` bug when it crashes when running several nodemons at once.

**Comment by catamphetamine** [comment]
They don't want to fix it by the way.
https://github.com/remy/nodemon/issues/709
So there's no other way other than delaying things.

**Comment by catamphetamine** [comment]
Oh, actually, seems that they finally merged someone's fix for that.
I'll remove the delay then since it's no longer needed.

**Comment by catamphetamine** [comment]
Removed `delay`s from the example project. Seems to be working on my machine.
