### ISSUE TITLE
Readme is difficult to follow

### ISSUE THREAD

**Issue by AndrewRayCode** [catamphetamine/universal-webpack#99]
The instructions say to create a `webpack.config.client.babel.js` file

Then without explaining why they say to use a `webpack.config.client.dev.babel.js` file

Scrolling up and looking for this file, and command-F-ing for this file in the readme reveal nothing

Only if you happen to keep reading (which I didn't do because I was stuck) would you find the `.dev` name

Then it links to `webpack.config.client.development.babel.js`, instead of `webpack.config.client.dev.babel.js`, adding some cognitive overhead of adding the file to your repo.

And it's not clear if you're supposed to copy/paste that whole config file verbatim to your project, or if it somehow comes for free with universal-webpack, and if you're supposed to copy it verbatim, what is the point of all the boilerplate in the file? Shouldn't that be hidden inside this library?

**Comment by catamphetamine** [comment]
No sht it is complicated as hell.
Rewrote the intro of the readme.
